services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: carrentaldb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourPassword4DbConection@
    ports:
      - '1433:1433'
    volumes:
      - ./src/config/create-database/create-database.sql:/tmp/create-database.sql

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: car-rental-tools
    depends_on:
      - sqlserver
    entrypoint: ["/bin/bash", "-c", "/opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P yourPassword4DbConection@ -i /tmp/create-database.sql || exit 1"]
    volumes:
      - ./src/config/create-database/create-database.sql:/tmp/create-database.sql
    healthcheck:
      test: ["CMD", "sqlcmd", "-U", "sa", "-P", "yourPassword4DbConection@", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-rental
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - sqlserver
    env_file:
      - .env